---
title: Editor Codebreaker
hero_image: images/banner.png
description:
  Analyse a frequency graph to crack the code, whilst learning about lists and functions
meta_title: Editor Codebreaker
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Use Python to crack a code whilst learning about lists and functions.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
landing: true
steps:
  - title: Reverse text
  - title: Create a dictionary
    completion:
      - engaged
  - title: Make a secret code
  - title: Encode text from a file
  - title: Get user input
  - title: Create a frequency analyser
    completion:
      - internal
  - title: Create a chart
    completion:
      - external
  - title: Challenge
    challenge: true
