---
title: Codebreaker
hero_image: images/banner.png
description:
  Analyse a frequency graph to crack the code, whilst learning about lists
  and functions
meta_title: Python coding projects for kids and teens | Code breaker
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Use Python to crack a code whilst learning about lists and functions.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - title: You will make
  - title: Encode the alphabet
  - title: Encode a message
    completion:
      - engaged
  - title: Create a menu
  - title: Encode text from a file
  - title: Create a frequency analyser
  - title: Analyse the frequency
    completion:
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Upgrade your project